// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentGatewayApp.Repositories;

namespace PaymentGatewayApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20190528141947_PaymentOption_seed")]
    partial class PaymentOption_seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("PaymentGatewayApp.Models.PaymentOption", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PaymentOptions");

                    b.HasData(
                        new { ID = 1, Name = "Online Banking" },
                        new { ID = 2, Name = "Gateway Wallet" },
                        new { ID = 3, Name = "Debit/Credit Card" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
